### PR TITLE
Major change: modified new data source

### LINKED ISSUE #18: Dataset source change (From Kaggle to VPD)
Hi team,

I have found a replacement of the data set using the Vancouver Police Department's official site. As such, we no longer require authentication from Kaggle and thus provide more flexibility at the later stage of milestones, e.g. Docker.

Here is the link: https://geodash.vpd.ca/opendata/crimedata_download/crimedata_csv_all_years.zip?disclaimer=on

Things I will update before final re-submission:
1. Update the download script
2. Re-run the analysis with the latest data set

### PR DESCRIPTION
**Pull request by thomassiu**
Hi all,

I have updated the source of the data set to The Vancouver Police Department's open data. The following are updated as part of this PR (Resolved #18):

1. README.md, removes Kaggle API, modified descriptions to the data set, and changed the license section
2. Removes the previous dataset and added the new one under data/raw
3. Modified data/src/download_data.py to support the download of both zip and non zip (csv) files.
4. Modified data/src/crime_in_vancouver_eda.ipynb to use this new data set, and filter year range up to 2020.

Besides, I have updated the file name of code of conduct so that github can automatically recognize it.

### CODE REVIEW

**Comment by jasmineortega** [comment]
Hi Thomas, everything looks good. Thanks for taking care of that!

**Comment by thomassiu** [comment]
Thank you! @jasmineortega  can you try to mark it as approved and I will merge it.

**Comment by jasmineortega** [comment]
Wait sorry do you mean label it? Edit:Nevermind I see it

**Review by jasmineortega — COMMENTED** [review]
Approved

**Comment by thomassiu** [comment]
Thanks @jasmineortega  It is merged.
You may create a new release as 0.0.2 and submit again 😃 I have confirmed with Florencia that we can advance the version for re-submission. 
Thank you!

**Comment by jasmineortega** [comment]
Great, submitted!

**Pull request merged**
