### PR TITLE
Tentative progress on literate code doc

### PR DESCRIPTION
**Pull request by jasmineortega**
I'm having difficult getting the pickle pipeline to print in R. And if there's 'PLACEHOLDER' or "..." anywhere it needs to be worked on

### CODE REVIEW

**Comment by jasmineortega** [comment]
(updated 11/27 8:45AM) 
To - do still:
[x] explain confusion matrix

**Review by thomassiu — APPROVED** [review]

**Comment by thomassiu** [comment]
Hi Jasmine,

What information do you want to put in the markdown from the pickle file?

**Comment by thomassiu** [comment]
may be we can output it as a table/png format. as the pickle object we have is literally the model itself for further prediction.

**Comment by jasmineortega** [comment]
Under results, there is a pipe_best.p! I suppose it's not absolutely required to use, but it would be nice to use in the analysis. 

Update: I have removed it. I describe the column transformers in the analysis anyway, so I think it will be ok.

**Comment by thomassiu** [comment]
pipe_best.p is actually the following object, which you cannot do anything with it. Therefore I am extracting an image instead, something like the following, which is a human readable of the pipe_best.p

best_LR_model
pipe_best = make_pipeline(preprocessor, best_results['best_model'])

**Review by thomassiu — APPROVED** [review]

**Pull request merged**
