### PR TITLE
Updated EDA and consolidation decision

### PR DESCRIPTION
**Pull request by sy25wang**
Update EDA see link here
https://github.com/sy25wang/DSCI_522_Crime_Prediction_Vancouver/tree/main/src

@RamiroMejia has some great ideas also in ipynb format, maybe we combine two together?
https://github.com/RamiroMejia/DSCI_522_Crime_Prediction_Vancouver/blob/main/EDA.ipynb
 
Feel free to share your EDA and thoughts

### CODE REVIEW

**Comment by jasmineortega** [comment]
I agree, I wonder if we can have more than 1 EDA in the repo? I think it would be easier than trying to translate from altair to R. What does everyone think?

**Comment by thomassiu** [comment]
Hi all, also we should split the data once it is loaded. See my version for your reference:
https://github.com/thomassiu/DSCI_522_Crime_Prediction_Vancouver/tree/thomas_eda/src

**Comment by thomassiu** [comment]
> I agree, I wonder if we can have more than 1 EDA in the repo? I think it would be easier than trying to translate from altair to R. What does everyone think?

Probably stick to 1 EDA file? And we may embed the R code in juypyter notebook, like how Joel did in 531.

**Comment by jasmineortega** [comment]
Sounds like a good compromise to me!

**Comment by thomassiu** [comment]
This is perfect now! Thank you @sy25wang and all!!!

**Comment by sy25wang** [comment]
Add ipynb file for all visualizations. Once merged, you may delete Rmd and pdf files

**Comment by RamiroMejia** [comment]
Good job! The plots are great

**Comment by jasmineortega** [comment]
Fantastic job, Shi Yan!

**Pull request merged**
